### ISSUE TITLE
A small problem about  PUE_labs's introduction

### ISSUE THREAD

**Issue by ghost** [cyyzero/PUE_labs#1]
Why do you think only junior brother apprentice will find this homework while junior sister apprentice can't deserve to have a name?

**Comment by cyyzero** [comment]
😹Nono

**Comment by cyyzero** [comment]
😂Just a joke

**Comment by mu001999** [comment]
I suspect that you are suspected of gender discrimination

**Comment by mu001999** [comment]
Three years have passed and there is still no change!

**Comment by cyyzero** [comment]
> Three years have passed and there is still no change!

I can't agree
